name: Build Windows EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyinstaller-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Red Support It'
          options: >
            --onefile
            --windowed
            --noconsole
            --name "Red Support It"
            --add-data "logo.png;."
